set_property IOSTANDARD "LVCMOS33" [get_ports "CLK"]
set_property PACKAGE_PIN "M19" [get_ports "CLK"]

set_property IOSTANDARD "LVCMOS33" [get_ports "RESETn"]
set_property PACKAGE_PIN "Y18" [get_ports "RESETn"]

set_property IOSTANDARD "LVCMOS33" [get_ports "PushButton[*]"]
set_property PACKAGE_PIN "AA18" [get_ports "PushButton[0]"]
set_property PACKAGE_PIN "Y19" [get_ports "PushButton[1]"]
set_property PACKAGE_PIN "AA19" [get_ports "PushButton[2]"]

set_property IOSTANDARD "LVCMOS33" [get_ports "DIPSwitch[*]"]
set_property PACKAGE_PIN  "Y20" [get_ports "DIPSwitch[0]"]
set_property PACKAGE_PIN  "Y21" [get_ports "DIPSwitch[1]"]
set_property PACKAGE_PIN  "AB19" [get_ports "DIPSwitch[2]"]
set_property PACKAGE_PIN  "AB20" [get_ports "DIPSwitch[3]"]
set_property PACKAGE_PIN  "AA22" [get_ports "DIPSwitch[4]"]
set_property PACKAGE_PIN  "AB22" [get_ports "DIPSwitch[5]"]
set_property PACKAGE_PIN  "AA21" [get_ports "DIPSwitch[6]"]
set_property PACKAGE_PIN  "AB21" [get_ports "DIPSwitch[7]"]

set_property IOSTANDARD "LVCMOS33" [get_ports "LED[*]"]
set_property PACKAGE_PIN  "T16" [get_ports "LED[0]"]
set_property PACKAGE_PIN  "T17" [get_ports "LED[1]"]
set_property PACKAGE_PIN  "R19" [get_ports "LED[2]"]
set_property PACKAGE_PIN  "T19" [get_ports "LED[3]"]
set_property PACKAGE_PIN  "R18" [get_ports "LED[4]"]
set_property PACKAGE_PIN  "T18" [get_ports "LED[5]"]
set_property PACKAGE_PIN  "P16" [get_ports "LED[6]"]
set_property PACKAGE_PIN  "R16" [get_ports "LED[7]"]
