
set_property IOSTANDARD "LVCMOS33" [get_ports "LED[*]"] 
set_property PACKAGE_PIN "T16" [get_ports "LED[7]"]
set_property PACKAGE_PIN "T17" [get_ports "LED[6]"]
set_property PACKAGE_PIN "R19" [get_ports "LED[5]"]
set_property PACKAGE_PIN "T19" [get_ports "LED[4]"]
set_property PACKAGE_PIN "R18" [get_ports "LED[3]"]
set_property PACKAGE_PIN "T18" [get_ports "LED[2]"]
set_property PACKAGE_PIN "P16" [get_ports "LED[1]"]
set_property PACKAGE_PIN "R16" [get_ports "LED[0]"]

set_property IOSTANDARD "LVCMOS33" [get_ports "PB[*]"]
set_property PACKAGE_PIN "AA19" [get_ports "PB[3]"]
set_property PACKAGE_PIN "Y19" [get_ports "PB[2]"]
set_property PACKAGE_PIN "AA18" [get_ports "PB[1]"]
set_property PACKAGE_PIN "Y18" [get_ports "PB[0]"]
