# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ch12_ps_tftlcd/ch12_ps_tftlcd.srcs/sources_1/ip/bufferram/bufferram.xci
# IP: The module: 'bufferram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ch12_ps_tftlcd/ch12_ps_tftlcd.srcs/sources_1/ip/bufferram/bufferram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bufferram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/ch12_ps_tftlcd/ch12_ps_tftlcd.srcs/sources_1/ip/bufferram/bufferram.xci
# IP: The module: 'bufferram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ch12_ps_tftlcd/ch12_ps_tftlcd.srcs/sources_1/ip/bufferram/bufferram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bufferram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
