webtalk_init -webtalk_dir D:\\single_camera_zynq7020\\project_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "È­ 7¿ù 14 17:26:38 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210947184_0_0_532" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3mfrmed39g7h6l8vopdjrcb9hq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_19" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "19" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3399 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1436862376390" -context "sdk\\\\hardware/1436862376390"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1436862376390"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1436862376390"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1436862376390"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1436862376390"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1436862376390"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1436862376390"
webtalk_transmit -clientid 2540570565 -regid "210947184_0_0_532" -xml D:\\single_camera_zynq7020\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\single_camera_zynq7020\\project_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\single_camera_zynq7020\\project_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
