# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work_edu/ch13_pl_cis/ch13_pl_cis.srcs/sources_1/ip/RAM_camera/RAM_camera.xci
# IP: The module: 'RAM_camera' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work_edu/ch13_pl_cis/ch13_pl_cis.srcs/sources_1/ip/RAM_camera/RAM_camera_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_camera'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/work_edu/ch13_pl_cis/ch13_pl_cis.srcs/sources_1/ip/RAM_camera/RAM_camera.xci
# IP: The module: 'RAM_camera' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work_edu/ch13_pl_cis/ch13_pl_cis.srcs/sources_1/ip/RAM_camera/RAM_camera_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RAM_camera'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
