#OSC 25
set_property PACKAGE_PIN M19 [get_ports OSC_25]
set_property IOSTANDARD LVCMOS33 [get_ports OSC_25]
#GPIO 0, reset
set_property PACKAGE_PIN Y18 [get_ports nreset]
set_property IOSTANDARD LVCMOS33 [get_ports nreset]

#lcd
set_property PACKAGE_PIN L17 [get_ports lcd_clk]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_clk]
set_property PACKAGE_PIN N17 [get_ports lcd_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_hsync]
set_property PACKAGE_PIN M17 [get_ports lcd_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_vsync]
set_property PACKAGE_PIN U22 [get_ports lcd_de_out]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_de_out]
set_property PACKAGE_PIN T22 [get_ports {lcd_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN U21 [get_ports {lcd_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN T21 [get_ports {lcd_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN K20 [get_ports {lcd_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN K19 [get_ports {lcd_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN L22 [get_ports {lcd_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN L21 [get_ports {lcd_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN K21 [get_ports {lcd_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN J20 [get_ports {lcd_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN J22 [get_ports {lcd_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN J21 [get_ports {lcd_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN K18 [get_ports {lcd_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN J18 [get_ports {lcd_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN M16 [get_ports {lcd_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN M15 [get_ports {lcd_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN N18 [get_ports {lcd_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN W22 [get_ports lcd_tpower]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_tpower]

##dip switch
#set_property PACKAGE_PIN Y20 [get_ports sel_cam]
#set_property IOSTANDARD LVCMOS33 [get_ports sel_cam]

#camera0
#I2C0, GPIO 0, 1
set_property PACKAGE_PIN F16 [get_ports iic_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_scl_io]
set_property PACKAGE_PIN E16 [get_ports iic_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports iic_0_sda_io]

set_property PACKAGE_PIN V5 [get_ports cam0_PWDN]
set_property IOSTANDARD LVCMOS33 [get_ports cam0_PWDN]
set_property PACKAGE_PIN V4 [get_ports cam0_reset]
set_property IOSTANDARD LVCMOS33 [get_ports cam0_reset]
set_property PACKAGE_PIN Y16 [get_ports cam0_mclk]
set_property IOSTANDARD LVCMOS33 [get_ports cam0_mclk]
set_property PACKAGE_PIN W17 [get_ports cam0_hsync]
set_property IOSTANDARD LVCMOS33 [get_ports cam0_hsync]
set_property PACKAGE_PIN W18 [get_ports cam0_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports cam0_vsync]
set_property PACKAGE_PIN W16 [get_ports cam0_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports cam0_pclk]

set_property PACKAGE_PIN U15 [get_ports {cam0_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam0_data[0]}]
set_property PACKAGE_PIN U16 [get_ports {cam0_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam0_data[1]}]
set_property PACKAGE_PIN U17 [get_ports {cam0_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam0_data[2]}]
set_property PACKAGE_PIN V17 [get_ports {cam0_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam0_data[3]}]
set_property PACKAGE_PIN AA17 [get_ports {cam0_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam0_data[4]}]
set_property PACKAGE_PIN AB17 [get_ports {cam0_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam0_data[5]}]
set_property PACKAGE_PIN AA16 [get_ports {cam0_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam0_data[6]}]
set_property PACKAGE_PIN AB16 [get_ports {cam0_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cam0_data[7]}]


##camera1
##I2C1, GPIO 2, 3
#set_property PACKAGE_PIN D16 [get_ports iic_1_scl_io]
#set_property IOSTANDARD LVCMOS33 [get_ports iic_1_scl_io]
#set_property PACKAGE_PIN D17 [get_ports iic_1_sda_io]
#set_property IOSTANDARD LVCMOS33 [get_ports iic_1_sda_io]
