# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.cache/wt [current_project]
set_property parent.project_path D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib {
  D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/sources_1/new/textlcd.v
  D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/sources_1/bd/system/hdl/system_wrapper.v
  D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/sources_1/new/top.v
}
read_xdc D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files D:/FINISH/ch8_pl_TextLCD/ch8_pl_TextLCD.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7z020clg484-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
