# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.cache/wt [current_project]
set_property parent.project_path D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.runs/CHAR_DPRAM_synth_1/CHAR_DPRAM.dcp
set_property used_in_implementation false [get_files D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.runs/CHAR_DPRAM_synth_1/CHAR_DPRAM.dcp]
add_files D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib {
  D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/new/CHAR_GEN_ROM.v
  D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/new/CHAR_GEN.v
  D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/new/VIDEO_OUT.v
  D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/new/SVGA_DEFINES.v
  D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/new/SVGA_TIMING_GENERATOR.v
  D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/new/CHAR_DISPLAY.v
  D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/imports/hdl/system_wrapper.v
  D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/new/CHAR_TOP.v
}
read_xdc D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/constrs_1/new/CHAR_TOP.xdc
set_property used_in_implementation false [get_files D:/FINISH/ch14_pl_ascii/ch14_pl_ascii.srcs/constrs_1/new/CHAR_TOP.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file CHAR_TOP.hwdef }
synth_design -top CHAR_TOP -part xc7z020clg484-1
write_checkpoint -noxdef CHAR_TOP.dcp
catch { report_utilization -file CHAR_TOP_utilization_synth.rpt -pb CHAR_TOP_utilization_synth.pb }
