webtalk_init -webtalk_dir D:\\FINISH\\ch12_ps_tftlcd\\ch12_ps_tftlcd.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "¿ù 2¿ù 23 11:09:08 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210947184_0_0_976" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "569lt6hrj2k1de4p02ovbunron" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_58" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "58" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 7600)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3311 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1424657075083" -context "sdk\\\\hardware/1424657075083"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1424657075083"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1424657075083"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4_63036" -context "sdk\\\\hardware/1424657075083"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1424657075083"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1424657075083"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1424657075083"
webtalk_add_data -client sdk -key uid -value "1424657121434" -context "sdk\\\\bsp/1424657121434"
webtalk_add_data -client sdk -key hwid -value "1424657075083" -context "sdk\\\\bsp/1424657121434"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1424657121434"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1424657121434"
webtalk_add_data -client sdk -key uid -value "1424657122664" -context "sdk\\\\application/1424657122664"
webtalk_add_data -client sdk -key hwid -value "1424657075083" -context "sdk\\\\application/1424657122664"
webtalk_add_data -client sdk -key bspid -value "1424657121434" -context "sdk\\\\application/1424657122664"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1424657122664"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1424657122664"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1424657122664"
webtalk_transmit -clientid 3908658583 -regid "210947184_0_0_976" -xml D:\\FINISH\\ch12_ps_tftlcd\\ch12_ps_tftlcd.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\FINISH\\ch12_ps_tftlcd\\ch12_ps_tftlcd.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\FINISH\\ch12_ps_tftlcd\\ch12_ps_tftlcd.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
