set_property IOSTANDARD "LVCMOS33" [get_ports "clk_in"] 
set_property PACKAGE_PIN "M19" [get_ports "clk_in"]

set_property IOSTANDARD "LVCMOS33" [get_ports "resetn"] 
set_property PACKAGE_PIN "Y18" [get_ports "resetn"]

set_property IOSTANDARD "LVCMOS33" [get_ports "led_out[*]"] 
set_property PACKAGE_PIN "T16" [get_ports "led_out[7]"]
set_property PACKAGE_PIN "T17" [get_ports "led_out[6]"]
set_property PACKAGE_PIN "R19" [get_ports "led_out[5]"]
set_property PACKAGE_PIN "T19" [get_ports "led_out[4]"]
set_property PACKAGE_PIN "R18" [get_ports "led_out[3]"]
set_property PACKAGE_PIN "T18" [get_ports "led_out[2]"]
set_property PACKAGE_PIN "P16" [get_ports "led_out[1]"]
set_property PACKAGE_PIN "R16" [get_ports "led_out[0]"]

set_property IOSTANDARD "LVCMOS33" [get_ports "segout[*]"] 
set_property PACKAGE_PIN "Y6" [get_ports "segout[7]"]
set_property PACKAGE_PIN "Y5" [get_ports "segout[6]"]
set_property PACKAGE_PIN "AA7" [get_ports "segout[5]"]
set_property PACKAGE_PIN "AA6" [get_ports "segout[4]"]
set_property PACKAGE_PIN "AB2" [get_ports "segout[3]"]
set_property PACKAGE_PIN "AB1" [get_ports "segout[2]"]
set_property PACKAGE_PIN "AB5" [get_ports "segout[1]"]
set_property PACKAGE_PIN "AB4" [get_ports "segout[0]"]

set_property IOSTANDARD "LVCMOS33" [get_ports "segcom[*]"] 
set_property PACKAGE_PIN "AB7" [get_ports "segcom[7]"]
set_property PACKAGE_PIN "AB6" [get_ports "segcom[6]"]
set_property PACKAGE_PIN "Y4" [get_ports "segcom[5]"]
set_property PACKAGE_PIN "AA4" [get_ports "segcom[4]"]
set_property PACKAGE_PIN "R6" [get_ports "segcom[3]"]
set_property PACKAGE_PIN "T6" [get_ports "segcom[2]"]
set_property PACKAGE_PIN "T4" [get_ports "segcom[1]"]
set_property PACKAGE_PIN "U4" [get_ports "segcom[0]"]
