# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/work_edu/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/ip/CHAR_DPRAM/CHAR_DPRAM.xci
# IP: The module: 'CHAR_DPRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work_edu/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/ip/CHAR_DPRAM/CHAR_DPRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CHAR_DPRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/work_edu/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/ip/CHAR_DPRAM/CHAR_DPRAM.xci
# IP: The module: 'CHAR_DPRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/work_edu/ch14_pl_ascii/ch14_pl_ascii.srcs/sources_1/ip/CHAR_DPRAM/CHAR_DPRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CHAR_DPRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
